create or replace function public.valid_drink_order_items(value jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select
    jsonb_typeof(value) = 'array'
    and jsonb_array_length(value) between 1 and 3
    and not exists (
      select 1
      from jsonb_array_elements(value) as item
      where item ->> 'id' not in ('iced-tea', 'lemonade', 'ade')
        or item ->> 'name' not in ('아이스티', '레모네이드', '오늘의 에이드')
        or not (item ->> 'quantity' ~ '^[1-9]$')
    );
$$;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity,
  items jsonb not null check (public.valid_drink_order_items(items)),
  note text not null default '' check (char_length(note) <= 80),
  status text not null default 'new' check (status in ('new', 'making', 'done', 'canceled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);

alter table public.orders enable row level security;

revoke all on table public.orders from anon, authenticated;
grant select, insert on table public.orders to anon, authenticated;
grant update (status, updated_at) on table public.orders to anon, authenticated;
grant usage, select on sequence public.orders_order_number_seq to anon, authenticated;

drop policy if exists "orders are readable" on public.orders;
create policy "orders are readable"
on public.orders for select
to anon, authenticated
using (true);

drop policy if exists "orders can be created" on public.orders;
create policy "orders can be created"
on public.orders for insert
to anon, authenticated
with check (status = 'new');

drop policy if exists "order status can be updated" on public.orders;
create policy "order status can be updated"
on public.orders for update
to anon, authenticated
using (true)
with check (status in ('new', 'making', 'done', 'canceled'));

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
end $$;
