create or replace function public.valid_drink_order_items(value jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select
    jsonb_typeof(value) = 'array'
    and jsonb_array_length(value) between 1 and 20
    and not exists (
      select 1
      from jsonb_array_elements(value) as item
      where coalesce(item ->> 'id', '') = ''
        or coalesce(item ->> 'name', '') = ''
        or not (item ->> 'quantity' ~ '^[1-9]$')
    )
    and (
      select count(distinct item ->> 'id')
      from jsonb_array_elements(value) as item
    ) = jsonb_array_length(value);
$$;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity,
  items jsonb not null check (public.valid_drink_order_items(items)),
  note text not null default '' check (char_length(note) <= 80),
  status text not null default 'new' check (status in ('new', 'making', 'done', 'canceled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);

create table if not exists public.menu_items (
  id text primary key default gen_random_uuid()::text,
  name text not null check (char_length(trim(name)) between 1 and 30),
  icon text not null default '🥤' check (char_length(trim(icon)) between 1 and 12),
  is_available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists menu_items_name_key on public.menu_items (lower(name));

insert into public.menu_items (id, name, icon, sort_order)
values
  ('iced-tea', '아이스티', '🧊', 1),
  ('lemonade', '레모네이드', '🍋', 2),
  ('ade', '오늘의 에이드', '🥤', 3)
on conflict (id) do nothing;

alter table public.orders enable row level security;
alter table public.menu_items enable row level security;

revoke all on table public.orders from anon, authenticated;
revoke all on sequence public.orders_order_number_seq from anon, authenticated;
revoke all on table public.menu_items from anon, authenticated;

drop policy if exists "orders are readable" on public.orders;
drop policy if exists "orders can be created" on public.orders;
drop policy if exists "order status can be updated" on public.orders;

create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;
revoke all on schema private from public;

create table if not exists private.admin_config (
  id boolean primary key default true check (id),
  pin_hash text not null
);

alter table private.admin_config enable row level security;
revoke all on table private.admin_config from public, anon, authenticated;

create or replace function private.set_admin_pin(value text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if value !~ '^[0-9]{4,12}$' then
    raise exception 'admin pin must contain 4 to 12 digits';
  end if;

  insert into private.admin_config (id, pin_hash)
  values (true, extensions.crypt(value, extensions.gen_salt('bf', 10)))
  on conflict (id) do update set pin_hash = excluded.pin_hash;
end;
$$;

revoke all on function private.set_admin_pin(text) from public;

create or replace function private.admin_pin_ok(value text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select extensions.crypt(value, pin_hash) = pin_hash from private.admin_config where id = true),
    false
  );
$$;

revoke all on function private.admin_pin_ok(text) from public;

create or replace function public.create_order(order_items jsonb, order_note text default '')
returns public.orders
language plpgsql
security definer
set search_path = ''
as $$
declare
  created public.orders;
begin
  if not public.valid_drink_order_items(order_items) then
    raise exception 'invalid order items' using errcode = '22023';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(order_items) as item
    left join public.menu_items as menu
      on menu.id = item ->> 'id'
      and menu.name = item ->> 'name'
    where menu.id is null or not menu.is_available
  ) then
    raise exception 'menu item unavailable' using errcode = '22023';
  end if;

  insert into public.orders (items, note)
  values (order_items, trim(left(coalesce(order_note, ''), 80)))
  returning * into created;
  return created;
end;
$$;

create or replace function public.list_menu_items()
returns setof public.menu_items
language sql
stable
security definer
set search_path = ''
as $$
  select * from public.menu_items order by sort_order, created_at;
$$;

create or replace function public.get_order(order_id uuid)
returns public.orders
language sql
stable
security definer
set search_path = ''
as $$
  select * from public.orders where id = order_id;
$$;

create or replace function public.admin_check_pin(pin text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.admin_pin_ok(pin);
$$;

create or replace function public.admin_list_orders(pin text)
returns setof public.orders
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;
  return query select * from public.orders order by created_at desc limit 200;
end;
$$;

create or replace function public.admin_update_order(pin text, order_id uuid, next_status text)
returns public.orders
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated public.orders;
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;
  if next_status not in ('making', 'done', 'canceled') then
    raise exception 'invalid order status';
  end if;

  update public.orders
  set status = next_status, updated_at = now()
  where id = order_id
  returning * into updated;
  return updated;
end;
$$;

create or replace function public.admin_add_menu(pin text, item_name text, item_icon text default '🥤')
returns public.menu_items
language plpgsql
security definer
set search_path = ''
as $$
declare
  created public.menu_items;
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;
  if char_length(trim(coalesce(item_name, ''))) not between 1 and 30 then
    raise exception 'menu name must contain 1 to 30 characters' using errcode = '22023';
  end if;
  if char_length(trim(coalesce(item_icon, ''))) not between 1 and 12 then
    raise exception 'menu icon must contain 1 to 12 characters' using errcode = '22023';
  end if;

  insert into public.menu_items (name, icon, sort_order)
  values (
    trim(item_name),
    trim(item_icon),
    coalesce((select max(sort_order) + 1 from public.menu_items), 1)
  )
  returning * into created;
  return created;
end;
$$;

create or replace function public.admin_set_menu_available(pin text, menu_id text, available boolean)
returns public.menu_items
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated public.menu_items;
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;

  update public.menu_items
  set is_available = available
  where id = menu_id
  returning * into updated;
  return updated;
end;
$$;

create or replace function public.admin_remove_menu(pin text, menu_id text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  removed_count integer;
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;

  delete from public.menu_items where id = menu_id;
  get diagnostics removed_count = row_count;
  return removed_count = 1;
end;
$$;

revoke all on function public.create_order(jsonb, text) from public;
revoke all on function public.list_menu_items() from public;
revoke all on function public.get_order(uuid) from public;
revoke all on function public.admin_check_pin(text) from public;
revoke all on function public.admin_list_orders(text) from public;
revoke all on function public.admin_update_order(text, uuid, text) from public;
revoke all on function public.admin_add_menu(text, text, text) from public;
revoke all on function public.admin_set_menu_available(text, text, boolean) from public;
revoke all on function public.admin_remove_menu(text, text) from public;

grant execute on function public.create_order(jsonb, text) to anon, authenticated;
grant execute on function public.list_menu_items() to anon, authenticated;
grant execute on function public.get_order(uuid) to anon, authenticated;
grant execute on function public.admin_check_pin(text) to anon, authenticated;
grant execute on function public.admin_list_orders(text) to anon, authenticated;
grant execute on function public.admin_update_order(text, uuid, text) to anon, authenticated;
grant execute on function public.admin_add_menu(text, text, text) to anon, authenticated;
grant execute on function public.admin_set_menu_available(text, text, boolean) to anon, authenticated;
grant execute on function public.admin_remove_menu(text, text) to anon, authenticated;

-- Run this separately in the SQL Editor with the real PIN; do not commit it:
-- select private.set_admin_pin('replace-with-your-pin');
