create or replace function public.valid_drink_order_items(value jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select
    jsonb_typeof(value) = 'array'
    and jsonb_array_length(value) between 1 and 20
    and not exists (
      select 1
      from jsonb_array_elements(value) as item
      where coalesce(item ->> 'id', '') = ''
        or coalesce(item ->> 'name', '') = ''
        or not (item ->> 'quantity' ~ '^[1-9]$')
    )
    and (
      select count(distinct item ->> 'id')
      from jsonb_array_elements(value) as item
    ) = jsonb_array_length(value);
$$;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity,
  device_id uuid,
  order_day date not null default ((now() at time zone 'Asia/Seoul')::date),
  customer_name text not null default '이름 없음' check (char_length(trim(customer_name)) between 1 and 20),
  party_size smallint not null default 1 check (party_size between 1 and 20),
  items jsonb not null check (public.valid_drink_order_items(items)),
  note text not null default '' check (char_length(note) <= 80),
  status text not null default 'new' check (status in ('new', 'making', 'done', 'canceled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

alter table public.orders
  add column if not exists device_id uuid,
  add column if not exists order_day date not null default ((now() at time zone 'Asia/Seoul')::date),
  add column if not exists customer_name text not null default '이름 없음'
  check (char_length(trim(customer_name)) between 1 and 20),
  add column if not exists party_size smallint not null default 1
  check (party_size between 1 and 20);

create unique index if not exists orders_one_active_per_device_day
  on public.orders (device_id, order_day)
  where device_id is not null and status <> 'canceled';

create index if not exists orders_created_at_idx on public.orders (created_at desc);

create table if not exists public.menu_items (
  id text primary key default gen_random_uuid()::text,
  name text not null check (char_length(trim(name)) between 1 and 30),
  icon text not null default '🥤' check (char_length(trim(icon)) between 1 and 12),
  category text not null default 'NON SODA' check (category in ('ADE', 'NON SODA')),
  is_available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.menu_items
  add column if not exists category text not null default 'NON SODA'
  check (category in ('ADE', 'NON SODA'));

create unique index if not exists menu_items_name_key on public.menu_items (lower(name));

insert into public.menu_items (id, name, icon, category, sort_order)
values
  ('iced-tea', '아이스티', '🧊', 'NON SODA', 1),
  ('lemonade', '레모네이드', '🍋', 'ADE', 2),
  ('ade', '오늘의 에이드', '🥤', 'ADE', 3)
on conflict (id) do nothing;

update public.menu_items
set category = 'ADE'
where id in ('lemonade', 'ade') or name ilike 'ADE)%' or upper(icon) = 'ADE';

alter table public.orders enable row level security;
alter table public.menu_items enable row level security;

revoke all on table public.orders from anon, authenticated;
revoke all on sequence public.orders_order_number_seq from anon, authenticated;
revoke all on table public.menu_items from anon, authenticated;

drop policy if exists "orders are readable" on public.orders;
drop policy if exists "orders can be created" on public.orders;
drop policy if exists "order status can be updated" on public.orders;

create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;
revoke all on schema private from public;

create table if not exists private.admin_config (
  id boolean primary key default true check (id),
  pin_hash text not null
);

alter table private.admin_config enable row level security;
revoke all on table private.admin_config from public, anon, authenticated;

create or replace function private.set_admin_pin(value text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if value !~ '^[0-9]{4,12}$' then
    raise exception 'admin pin must contain 4 to 12 digits';
  end if;

  insert into private.admin_config (id, pin_hash)
  values (true, extensions.crypt(value, extensions.gen_salt('bf', 10)))
  on conflict (id) do update set pin_hash = excluded.pin_hash;
end;
$$;

revoke all on function private.set_admin_pin(text) from public;

create or replace function private.admin_pin_ok(value text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select extensions.crypt(value, pin_hash) = pin_hash from private.admin_config where id = true),
    false
  );
$$;

revoke all on function private.admin_pin_ok(text) from public;

drop function if exists public.create_order(jsonb, text);
drop function if exists public.create_order(jsonb, text, text, integer);

create or replace function public.create_order(
  order_items jsonb,
  order_note text,
  order_customer_name text,
  order_party_size integer,
  order_device_id uuid
)
returns public.orders
language plpgsql
security definer
set search_path = ''
as $$
declare
  created public.orders;
begin
  if not public.valid_drink_order_items(order_items) then
    raise exception 'invalid order items' using errcode = '22023';
  end if;
  if order_device_id is null then
    raise exception 'invalid device id' using errcode = '22023';
  end if;
  if char_length(trim(coalesce(order_customer_name, ''))) not between 1 and 20 then
    raise exception 'invalid customer name' using errcode = '22023';
  end if;
  if coalesce(order_party_size, 0) not between 1 and 20 then
    raise exception 'invalid party size' using errcode = '22023';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(order_items) as item
    left join public.menu_items as menu
      on menu.id = item ->> 'id'
      and menu.name = item ->> 'name'
    where menu.id is null or not menu.is_available
  ) then
    raise exception 'menu item unavailable' using errcode = '22023';
  end if;

  insert into public.orders (device_id, customer_name, party_size, items, note)
  values (
    order_device_id,
    trim(order_customer_name),
    order_party_size,
    order_items,
    trim(left(coalesce(order_note, ''), 80))
  )
  returning * into created;
  return created;
end;
$$;

create or replace function public.list_menu_items()
returns setof public.menu_items
language sql
stable
security definer
set search_path = ''
as $$
  select * from public.menu_items order by sort_order, created_at;
$$;

create or replace function public.get_order(order_id uuid)
returns public.orders
language sql
stable
security definer
set search_path = ''
as $$
  select * from public.orders where id = order_id;
$$;

drop function if exists public.get_order_by_code(text);

create function public.get_order_by_code(order_code text)
returns setof public.orders
language sql
stable
security definer
set search_path = ''
as $$
  select * from public.orders
  where trim(order_code) ~* '^[0-9a-f]{8}$'
    and order_day >= ((now() at time zone 'Asia/Seoul')::date - 7)
    and upper(substr(replace(id::text, '-', ''), 1, 8)) = upper(trim(order_code))
  order by created_at desc
  limit 1;
$$;

create or replace function public.admin_check_pin(pin text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.admin_pin_ok(pin);
$$;

create or replace function public.admin_list_orders(pin text)
returns setof public.orders
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;
  return query select * from public.orders order by created_at desc limit 200;
end;
$$;

create or replace function public.admin_list_orders_by_month(pin text, selected_month date)
returns setof public.orders
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  month_start date := date_trunc('month', selected_month)::date;
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;
  if selected_month is null then
    raise exception 'invalid month';
  end if;
  return query
    select * from public.orders
    where order_day >= month_start
      and order_day < (month_start + interval '1 month')::date
    order by created_at desc;
end;
$$;

create or replace function public.admin_update_order(pin text, order_id uuid, next_status text)
returns public.orders
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated public.orders;
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;
  if next_status not in ('making', 'done', 'canceled') then
    raise exception 'invalid order status';
  end if;

  update public.orders
  set status = next_status, updated_at = now()
  where id = order_id
  returning * into updated;
  return updated;
end;
$$;

create or replace function public.admin_add_menu(pin text, item_name text, item_icon text default '🥤')
returns public.menu_items
language plpgsql
security definer
set search_path = ''
as $$
declare
  created public.menu_items;
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;
  if char_length(trim(coalesce(item_name, ''))) not between 1 and 30 then
    raise exception 'menu name must contain 1 to 30 characters' using errcode = '22023';
  end if;
  if char_length(trim(coalesce(item_icon, ''))) not between 1 and 12 then
    raise exception 'menu icon must contain 1 to 12 characters' using errcode = '22023';
  end if;

  insert into public.menu_items (name, icon, sort_order)
  values (
    trim(item_name),
    trim(item_icon),
    coalesce((select max(sort_order) + 1 from public.menu_items), 1)
  )
  returning * into created;
  return created;
end;
$$;

create or replace function public.admin_add_menu(pin text, item_name text, item_icon text, item_category text)
returns public.menu_items
language plpgsql
security definer
set search_path = ''
as $$
declare
  created public.menu_items;
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;
  if char_length(trim(coalesce(item_name, ''))) not between 1 and 30 then
    raise exception 'menu name must contain 1 to 30 characters' using errcode = '22023';
  end if;
  if char_length(trim(coalesce(item_icon, ''))) not between 1 and 12 then
    raise exception 'menu icon must contain 1 to 12 characters' using errcode = '22023';
  end if;
  if item_category not in ('ADE', 'NON SODA') then
    raise exception 'invalid menu category' using errcode = '22023';
  end if;

  insert into public.menu_items (name, icon, category, sort_order)
  values (
    trim(item_name),
    trim(item_icon),
    item_category,
    coalesce((select max(sort_order) + 1 from public.menu_items), 1)
  )
  returning * into created;
  return created;
end;
$$;

create or replace function public.admin_rename_menu(pin text, menu_id text, item_name text)
returns public.menu_items
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated public.menu_items;
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;
  if char_length(trim(coalesce(item_name, ''))) not between 1 and 30 then
    raise exception 'menu name must contain 1 to 30 characters' using errcode = '22023';
  end if;

  update public.menu_items
  set name = trim(item_name)
  where id = menu_id
  returning * into updated;
  return updated;
end;
$$;

create or replace function public.admin_set_menu_available(pin text, menu_id text, available boolean)
returns public.menu_items
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated public.menu_items;
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;

  update public.menu_items
  set is_available = available
  where id = menu_id
  returning * into updated;
  return updated;
end;
$$;

create or replace function public.admin_reorder_menu(pin text, ordered_menu_ids text[])
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;
  if coalesce(cardinality(ordered_menu_ids), 0) <> (select count(*) from public.menu_items)
    or (select count(distinct id) from unnest(ordered_menu_ids) as ordered_id(id)) <> cardinality(ordered_menu_ids)
    or exists (select 1 from unnest(ordered_menu_ids) as ordered_id(id) where not exists (select 1 from public.menu_items where menu_items.id = ordered_id.id)) then
    raise exception 'invalid menu order' using errcode = '22023';
  end if;

  update public.menu_items as menu
  set sort_order = ordered.position
  from unnest(ordered_menu_ids) with ordinality as ordered(id, position)
  where menu.id = ordered.id;
  return true;
end;
$$;

create or replace function public.admin_remove_menu(pin text, menu_id text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  removed_count integer;
begin
  if not private.admin_pin_ok(pin) then
    raise exception 'invalid admin pin' using errcode = '42501';
  end if;

  delete from public.menu_items where id = menu_id;
  get diagnostics removed_count = row_count;
  return removed_count = 1;
end;
$$;

revoke all on function public.create_order(jsonb, text, text, integer, uuid) from public;
revoke all on function public.list_menu_items() from public;
revoke all on function public.get_order(uuid) from public;
revoke all on function public.get_order_by_code(text) from public;
revoke all on function public.admin_check_pin(text) from public;
revoke all on function public.admin_list_orders(text) from public;
revoke all on function public.admin_list_orders_by_month(text, date) from public;
revoke all on function public.admin_update_order(text, uuid, text) from public;
revoke all on function public.admin_add_menu(text, text, text) from public;
revoke all on function public.admin_add_menu(text, text, text, text) from public;
revoke all on function public.admin_rename_menu(text, text, text) from public;
revoke all on function public.admin_set_menu_available(text, text, boolean) from public;
revoke all on function public.admin_reorder_menu(text, text[]) from public;
revoke all on function public.admin_remove_menu(text, text) from public;

grant execute on function public.create_order(jsonb, text, text, integer, uuid) to anon, authenticated;
grant execute on function public.list_menu_items() to anon, authenticated;
grant execute on function public.get_order(uuid) to anon, authenticated;
grant execute on function public.get_order_by_code(text) to anon, authenticated;
grant execute on function public.admin_check_pin(text) to anon, authenticated;
grant execute on function public.admin_list_orders(text) to anon, authenticated;
grant execute on function public.admin_list_orders_by_month(text, date) to anon, authenticated;
grant execute on function public.admin_update_order(text, uuid, text) to anon, authenticated;
grant execute on function public.admin_add_menu(text, text, text) to anon, authenticated;
grant execute on function public.admin_add_menu(text, text, text, text) to anon, authenticated;
grant execute on function public.admin_rename_menu(text, text, text) to anon, authenticated;
grant execute on function public.admin_set_menu_available(text, text, boolean) to anon, authenticated;
grant execute on function public.admin_reorder_menu(text, text[]) to anon, authenticated;
grant execute on function public.admin_remove_menu(text, text) to anon, authenticated;

-- Run this separately in the SQL Editor with the real PIN; do not commit it:
-- select private.set_admin_pin('replace-with-your-pin');
